### ISSUE TITLE
copy/paste from word not working for alignment

### ISSUE THREAD

**Issue by boblz7** [Artem-Schander/quill-paste-smart#5] opened 2020-08-13 18:34 UTC
Everything pastes normally except alignments.
When I try copy paste from word file, with any of the four alignments it does not work, it just pastes it in normal left alignment.

My toolbar is defined in html rather than in js configuration:

> I've tried making toolbar through js also and it didn't work then aswell

```
<select class="ql-align">
  <option selected="selected"></option>
  <option value="center"></option>
  <option value="right"></option>
  <option value="justify"></option>
</select>
```
> To not make the text big I have only copied the html alignment code.

For configuration I used your example where I added only headers because I needed them
```
modules: {
   clipboard: {
     allowed: {
       tags: ['a', 'b', 'strong', 'u', 's', 'i', 'p', 'br', 'ul', 'ol', 'li', 'span', 'h1','h2','h3','h4','h5','h6',],
       attributes: ['href', 'rel', 'target', 'class']
     },
     keepSelection: false
   },
   toolbar : '#toolbar'
}
```

If I have made a mistake somewhere please tell me where and why was that the problem.

**Comment by artem-schander** [comment] 2020-08-13 19:56
Hi @boblz7 
I could imagine that MS Word does not do the same stuff for alignment as browsers would do.

I‘ll try to reproduce this issue tomorrow.
In the meantime you could create a sandbox, since I have no idea how you handle the toolbar.

**Comment by artem-schander** [comment] 2020-08-13 20:04
And one thing you could also try, is to add `style` to allowed attributes.
But be aware that than any inline style can be pasted in.

My personal opinion is to better strip more than end up with ugly user input.

**Comment by boblz7** [comment] 2020-08-14 12:25
Thanks for the quick answer @Artem-Schander 

I have made a fiddle: [FIDDLE](https://jsfiddle.net/boblz/6roky2ue)

I just want to clarify that when I copy something from a website which has some kind of alignment, it does work. I guess it's only from a word file when it doesn't work.

**Comment by artem-schander** [comment] 2020-08-14 12:44
Unfortunately it is not possible for me to get my hands on MS Word any time soon.
I'll try to figure out if there is a way to fix / work around this and let you know.

**Comment by boblz7** [comment] 2020-08-14 15:06
@Artem-Schander instead of downloading it, you could use word online if you have a hotmail / outlook account.

**Comment by artem-schander** [comment] 2020-08-14 15:49
No, I don't. I don't like proprietary software and try to avoid it as far as possible.
But I know someone. I just have no plans to meet him. However, there will be a way to tackle this.

**Comment by boblz7** [comment] 2020-08-14 16:47
Okay, was just trying to help. I will await your response :)

**Comment by artem-schander** [comment] 2021-04-10 17:34
Hi @boblz7,

I think I have a possible way to tackle you issue.
I've added [sanitizer hooks](https://github.com/cure53/DOMPurify#hooks) of the underlying lib [DOMPurify](https://github.com/cure53/DOMPurify) to the [lates release](https://www.npmjs.com/package/quill-paste-smart/v/1.4.0). Be aware: They are not that easy to use and it is possible to mess things up. But it should be worth trying.

I'm closing this issue, but feel free to reopen it if you like :)

**Closed as completed by artem-schander** 2021-04-10 17:34 UTC
