### ISSUE TITLE
Pasting multiline text from Outlook/Teams adds redundant space lines

### ISSUE THREAD

**Issue by FreddyMcRay** [Artem-Schander/quill-paste-smart#19] opened 2021-08-06 13:00 UTC
Here is an example of text from Outlook:
![image](https://user-images.githubusercontent.com/26858004/128513608-13e1f82e-dc8c-447a-8821-170ce737503f.png)
Copying the same text from browser doesn't allow to repro the issue. Just try to type smth similar.

I created a small repo that could help you reproduce the issue: https://github.com/FreddyMcRay/quill-smart-paste-repro
Pasting text that you could see above results in following:
![image](https://user-images.githubusercontent.com/26858004/128514012-d5be9e97-de74-4124-b7e5-66fd6de2485f.png)

**Comment by FreddyMcRay** [comment] 2021-08-06 13:04
From investigation I made walking through the dom [here](https://github.com/Artem-Schander/quill-paste-smart/blob/master/src/module.js#L345) wraps everything to <p> tags (including line breaks that are added by sanitizing) and that causes quill to show as true user content.

To solve that issue I rolled back to 1.4.4

**Comment by artem-schander** [comment] 2021-08-06 13:26
Hi @FreddyMcRay,
thank you for raising this issue. would you please send me the exact markup you're struggling with?
`br` tags should not be the issue.

**Comment by FreddyMcRay** [comment] 2021-08-10 09:06
Hi @Artem-Schander 
It's fairly simple:
```
Hi,

Test test test,

Test test


Test testttttt
Test test teststststststst



Test test tesssssst
```
But as I said do not copy it directly from browser trying to reproduce (it won't allow you to see the issue). You'd better try to type smth similar in outlook/teams on windows

**Comment by FreddyMcRay** [comment] 2021-08-10 09:07
I found out that email itself could be downloaded.
Hope it will help you to repro.
[repro-email.zip](https://github.com/Artem-Schander/quill-paste-smart/files/6960374/repro-email.zip)

**Comment by artem-schander** [comment] 2021-08-10 10:19
Nice. Thanks.

**Comment by SteveDowsett** [comment] 2022-02-25 11:17
This seems to be an issue for me also, pasting any content results in extra breaks? Any chance we could get an update on what the potential solution could be?

**Comment by artem-schander** [comment] 2022-02-26 11:50
Unfortunately I can not reproduce this issue. I have no access to a Windows computer (hence no outlook). I've tried with Apple Mail and I can try with Thunderbird on monday.

For now this is what I see:
<img width="504" alt="Bildschirmfoto 2022-02-26 um 12 43 38" src="https://user-images.githubusercontent.com/1243826/155842002-b5f14622-f64a-4f24-bbc2-9dd601840c2f.png">

And this is what I get after pasting (with and without Quill Paste Smart being enabled).
<img width="621" alt="Bildschirmfoto 2022-02-26 um 12 48 52" src="https://user-images.githubusercontent.com/1243826/155842060-9b7cf9fd-7784-4227-b124-8d74680995f6.png">

Everything seems fine to me.

Maybe someone who can reproduce this issue can craft a PR?

**Comment by artem-schander** [comment] 2023-07-20 20:54
I'm closing this issue for now. In case someone can reproduce/tackle this one, feel free to reopen.

**Closed as completed by artem-schander** 2023-07-20 20:54 UTC

**Comment by jonmarozick** [comment] 2024-07-10 19:35
Here's an html file I saved from Outlook: [outlook.zip](https://github.com/user-attachments/files/16167282/outlook.zip) that reproduces the extra line breaks issue.

The issue is in the substitute function. Here's some console.log() to show it.

```
      if (substitution && node.tagName && !DOMPurifyOptions.ALLOWED_TAGS.includes(node.tagName.toLowerCase())) {
        const tagName = node.tagName.toLowerCase();
            console.log('tagName: ' + tagName);
            console.log('substitution: ' + substitution);
            console.log('innerHTML: ' + node.innerHTML);
        if (headings.includes(tagName)) {
          node.innerHTML = `<${substitution}><b>${node.innerHTML}</b></${substitution}>`;
        } else if (blockElements.includes(tagName)) {
            console.log('blockElements.includes: ' + `<${substitution}>${node.innerHTML}</${substitution}>`);
            node.innerHTML = `<${substitution}>${node.innerHTML}</${substitution}>`;
        } else if (newLineElements.includes(tagName)) {
          node.innerHTML = `${node.innerHTML}<br>`;
        }
        console.log('after innerHTML: ' + node.innerHTML);
      }
```
The output is:
```
tagName: table
substitution: p
innerHTML: <tbody><tr><td style="padding: 0in 15pt 7.5pt;"><h2 align="center" style="margin: 0in; text-align: center; line-height: 42px;"><span style="font-size: 22.5pt; line-height: 52.5px; font-family: Lato, sans-serif; color: black;">&nbsp;Testing 1 2 3</span><span style="font-size: 22.5pt; line-height: 52.5px; font-family: Lato, sans-serif; color: black;"><o:p></o:p></span></h2></td></tr></tbody>
blockElements.includes: <p><tbody><tr><td style="padding: 0in 15pt 7.5pt;"><h2 align="center" style="margin: 0in; text-align: center; line-height: 42px;"><span style="font-size: 22.5pt; line-height: 52.5px; font-family: Lato, sans-serif; color: black;">&nbsp;Testing 1 2 3</span><span style="font-size: 22.5pt; line-height: 52.5px; font-family: Lato, sans-serif; color: black;"><o:p></o:p></span></h2></td></tr></tbody></p>
after innerHTML: <p></p><tbody><tr><td style="padding: 0in 15pt 7.5pt;"><h2 align="center" style="margin: 0in; text-align: center; line-height: 42px;"><span style="font-size: 22.5pt; line-height: 52.5px; font-family: Lato, sans-serif; color: black;">&nbsp;Testing 1 2 3</span><span style="font-size: 22.5pt; line-height: 52.5px; font-family: Lato, sans-serif; color: black;"><o:p></o:p></span></h2></td></tr></tbody><p></p>
```
Notice that the last log for after innerHTML has an opening and closing p tag. So, the assignment of innerHTML must fix invalid html. Removing the table and tfoot from blockElements improves the output. But, setting substituteBlockElements to false is still better. If I comment out all 3 lines that set innerHTML, it works like setting substituteBlockElements to false. I'm not sure how to fix it.

**Comment by jonmarozick** [comment] 2024-07-12 19:24
I added a removeConsecutiveSubstitutionTags setting to help with this in [PR 36](https://github.com/Artem-Schander/quill-paste-smart/pull/36)
